name: Build APK on Windows

on:
  push:
    branches:
      - prernarawat77
  pull_request:
    branches:
      - prernarawat77

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          C:\Users\runneradmin\.gradle\caches
          C:\Users\runneradmin\.gradle\wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build APK
      run: .\gradlew.bat assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: ERP-ionic-project\android\app\build\outputs\apk\release\app-release.apk
