name: ERP-ionic-project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  build:
    runs-on:  windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v20.16.01
        with:
          node-version: '14' # Set the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: ng build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: C:\Users\prath\OneDrive\Desktop\buildgithub
