name: Build Web Application

on:
  push:
    branches:
      - prernarawat77
  pull_request:
    branches:
      - prernarawat77

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install  # or yarn install if you use Yarn

    - name: Build application
      run: npm run build  # or your specific build command

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: ./build  # or the directory where your build output is located
